#!/bin/bash
#chkconfig:
#description: Startup and Shutdown script for storm cluster

PROGDIR=/usr/local/websrv/storm
PROGNAME=bin/storm

NIMBUSDIR=storm-nimbus
SUPERVISORDIRS=(
    storm-supervisor1
    storm-supervisor2
)
DESC="storm cluster daemon"
SCRIPTNAME=/etc/init.d/stormd

start(){
    # first, start nimbus daemon
    NIMBUSDAEMON=$PROGDIR/$NIMBUSDIR/$PROGNAME
    if test -x "$NIMBUSDAEMON"
    then
        echo -e "Starting $DESC: $NIMBUSDIR/$PROGNAME nimbus"
        if $NIMBUSDAEMON nimbus > /dev/null 2>&1 &
        then
            echo -e "OK"
        else
            echo -e "failed"
        fi
    else
        echo -e "Couldn't find Storm Nimbus Server($NIMBUSDAEMON)"
    fi
    #then, start ui daemon
    UIDAEMON=$PROGDIR/$NIMBUSDIR/$PROGNAME
    if test -x "$UIDAEMON"
    then
        echo -e "Starting $DESC: $NIMBUSDIR/$PROGNAME ui"
        if $UIDAEMON ui > /dev/null 2>&1 &
        then
            echo -e "OK"
        else
            echo -e "failed"
        fi
    else
        echo -e "Couldn't find Storm UI Server($UIDAEMON)"
    fi

    #finally, start supervisor daemon
    for SUPERVISORDIR in ${SUPERVISORDIRS[@]}
    do
        SUPERVISORDAEMON=$PROGDIR/$SUPERVISORDIR/$PROGNAME
        if test -x "$SUPERVISORDAEMON"
        then
            echo -e "Starting $DESC: $SUPERVISORDIR/$PROGNAME supervisor"
            if $SUPERVISORDAEMON supervisor >/dev/null 2>&1 &
            then
                echo -e "OK"
            else
                echo -e "failed"
            fi
        else
            echo -e "Couldn't find Storm Supervisor Server($SUPERVISORDAEMON)"
        fi
    done
}

stop()
{
    for PID in `ps axu|grep bin/storm|grep -v grep|awk '{print $2}'`
    do
        echo -e "Stoping $DESC: pid=$PID"
        if kill $PID
        then
            echo -e "OK"
        else
            echo -e "failed"
        fi
    done
}

restart()
{
    echo -e "Restart $DESC"
    stop
    start
}

list()
{
    ps aux | grep bin/storm | grep -v grep
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    list)
        list
        ;;

    *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|list}" >&2
        exit 1
        ;;
esac
exit 0
